### ISSUE TITLE
Outdated league/oauth2-server dependency

### ISSUE THREAD

**Issue by JanMikes** [lookyman/nette-oauth2-server-doctrine#15]
Hi, there is already version 7.0 of league/oauth2-server dependency out, meanwhile this library depends on version <5.1.4

Any plans to update?

**Comment by lookyman** [comment]
Sure, I just haven't gotten to it yet. You can send a PR if you want, otherwise I'll try to update it soon.

**Comment by lookyman** [comment]
I will try my damnedest to find some time this weekend. Thank you for holding on.

**Comment by lookyman** [comment]
@Lexinek I just released a new version.

**Comment by JanMikes** [comment]
Awesome, i will try it out, thank you!
