### ISSUE TITLE
How to store information if user has approved authorization?

### ISSUE THREAD

**Issue by Jigsik** [lookyman/nette-oauth2-server-doctrine#21]
There is no callback in handleApprove or handleDeny in ApproveControl.

Currently the user has to approve authorization on every login. Is it possible to approve authorization only once?

I only thought about adding callbacks onApprove and onDeny in ApproveControl.

Thanks in advance.

**Comment by lookyman** [comment]
I guess there is no such option. I think it's because if a user logs out and then tries to log back in, they sould be able to inspect the required scopes and approve the application again, in case those requirements changed.

**Comment by Jigsik** [comment]
OK. I understand. I will think about this later and close this issue for now. Thanks
